import { RestaurantHomeState } from "@/models/types";
import { createSlice } from "@reduxjs/toolkit";

// Initial state for the restaurant slice
const initialState: RestaurantHomeState = {
  loading: false,
  error: null,
  orders: [],
  menu: [],
};

// Create a Redux slice for the restaurant state
const restaurantHomeSlice = createSlice({
  name: "restauranHome",
  initialState: initialState,
  reducers: {
    // Action to update multiple aspects of the restaurant state
    restaurant: (state, action) => {
      // Update orders, menu data from the payload
      state.orders = action.payload.allOrdersData;
      state.menu = action.payload.foodData;
    },
    // Add the following reducers for delete, add, and update foodData
    deleteFood: (state, action) => {
      const deletedFoodId = action.payload;
      state.menu = state.menu.filter((food) => food._id !== deletedFoodId);
    },
    addFood: (state, action) => {
      const newFood = action.payload;
      state.menu = [...state.menu, newFood];
    },
    updateFood: (state, action) => {
      const updatedFood = action.payload;
      state.menu = state.menu.map((food) =>
        food._id === updatedFood.id ? updatedFood : food
      );
    },
  },
  extraReducers: (builder) => {},
});

// Export the actions generated by the restaurant slice
export const restaurantActions = restaurantHomeSlice.actions;

// Export the reducer function for the restaurant slice
export default restaurantHomeSlice.reducer;
